name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Mintlify CLI
        run: npm install -g mintlify

      - name: Start Mintlify dev server
        run: |
          mintlify dev > server.log 2>&1 &
          MINTLIFY_PID=$!
          echo "MINTLIFY_PID=$MINTLIFY_PID" >> $GITHUB_ENV
          echo "Waiting for Mintlify to start..."

          # Wait for server to be ready
          for i in {1..60}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Mintlify server is ready!"
              break
            fi
            echo "Waiting... ($i/60)"
            sleep 2
          done

          echo "Server log:"
          cat server.log

      - name: Scrape static site with httrack
        run: |
          sudo apt-get update
          sudo apt-get install -y httrack

          mkdir -p _site
          httrack http://localhost:3000 \
            -O _site \
            -v \
            -%e0 \
            -N0 \
            -%P \
            -c10 \
            -T60 \
            -R4 \
            -%s \
            '+*localhost:3000/*' \
            -'*localhost:3000/api/*' \
            -'*localhost:3000/_next/static/chunks/*'

      - name: Stop Mintlify
        if: always()
        run: |
          kill ${{ env.MINTLIFY_PID }} || true
          cat server.log || true

      - name: Organize files for GitHub Pages
        run: |
          # Move files from localhost:3000 subdirectory to root if it exists
          if [ -d "_site/localhost_3000" ]; then
            mv _site/localhost_3000/* _site/ 2>/dev/null || true
            rmdir _site/localhost_3000 || true
          fi

          if [ -d "_site/localhost:3000" ]; then
            mv "_site/localhost:3000"/* _site/ 2>/dev/null || true
            rmdir "_site/localhost:3000" || true
          fi

          # Add .nojekyll file
          touch _site/.nojekyll

          # List what we have
          echo "Contents of _site:"
          ls -la _site/

      - name: Fix links for GitHub Pages
        run: |
          cd _site
          # Remove localhost references and fix paths
          find . -type f \( -name "*.html" -o -name "*.css" -o -name "*.js" \) -exec sed -i \
            -e 's|http://localhost:3000||g' \
            -e 's|href="/|href="/test-mintlify/|g' \
            -e 's|src="/|src="/test-mintlify/|g' \
            -e 's|url(/|url(/test-mintlify/|g' \
            -e 's|/test-mintlify/test-mintlify|/test-mintlify|g' \
            {} \;

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          force_orphan: true
