name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Mintlify CLI
        run: npm install -g mintlify

      - name: Start Mintlify dev server
        run: |
          mintlify dev &
          MINTLIFY_PID=$!
          echo "MINTLIFY_PID=$MINTLIFY_PID" >> $GITHUB_ENV
          echo "Waiting for Mintlify to start..."
          sleep 30

      - name: Scrape static site
        run: |
          wget --recursive \
               --no-parent \
               --page-requisites \
               --html-extension \
               --convert-links \
               --restrict-file-names=windows \
               --domains localhost \
               --no-host-directories \
               --directory-prefix=_site \
               http://localhost:3000/

      - name: Stop Mintlify
        if: always()
        run: kill ${{ env.MINTLIFY_PID }} || true

      - name: Fix links and paths for GitHub Pages
        run: |
          cd _site
          # Remove localhost references
          find . -name "*.html" -type f -exec sed -i 's|http://localhost:3000||g' {} \;
          # Ensure all absolute paths include /test-mintlify prefix
          find . -name "*.html" -type f -exec sed -i 's|href="/\([^"]*\)"|href="/test-mintlify/\1"|g' {} \;
          find . -name "*.html" -type f -exec sed -i 's|src="/\([^"]*\)"|src="/test-mintlify/\1"|g' {} \;
          # Fix double slashes that might have been created
          find . -name "*.html" -type f -exec sed -i 's|/test-mintlify/test-mintlify|/test-mintlify|g' {} \;

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          force_orphan: true
